apiVersion: v1
kind: Service
metadata:
  name: django-gateway-api
spec:
  selector:
    app: django-gateway-api
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-gateway-api
spec:
  selector:
    matchLabels:
      app: django-gateway-api
  template:
    metadata:
      labels:
        app: django-gateway-api
    spec:
      containers:
        - name: django-gateway-api
          image: jcortizs/django_gateway_api
          ports:
            - containerPort: 80
