# Generated by Django 4.2.5 on 2023-10-08 20:48
from django.utils import timezone

from django.db import migrations, models
from ..models import connection


def insert_connections(apps, schema_editor):
    # Create a new book object and save it
    connection.objects.create(name="courses API GET", process="Courses", server="localhost",
                              port=8090, method="GET", createdon=timezone.now(), createdby="jco", ind_activo=1)

    connection.objects.create(name="courses API POST", process="Courses", server="localhost",
                              port=8090, method="POST", createdon=timezone.now(), createdby="jco")

    connection.objects.create(name="courses API PUT", process="Courses", server="localhost",
                              port=8090, method="PUT", createdon=timezone.now(), createdby="jco")

    connection.objects.create(name="courses API DELETE", process="Courses", server="localhost",
                              port=8090, method="DELETE", createdon=timezone.now(), createdby="jco")

    connection.objects.create(name="resources API GET", process="Files", server="localhost",
                              port=8080, method="GET", createdon=timezone.now(), createdby="jco", ind_activo=1)

    connection.objects.create(name="resources API POST", process="Files", server="localhost",
                              port=8080, method="POST", createdon=timezone.now(), createdby="jco")

    connection.objects.create(name="resources API PUT", process="Files", server="localhost",
                              port=8080, method="PUT", createdon=timezone.now(), createdby="jco")

    connection.objects.create(name="resources API DELETE", process="Files", server="localhost",
                              port=8080, method="DELETE", createdon=timezone.now(), createdby="jco")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('process', models.CharField(max_length=25)),
                ('action', models.CharField(max_length=25, null=True)),
                ('server', models.CharField(max_length=250)),
                ('port', models.IntegerField(null=True)),
                ('method', models.CharField(max_length=10)),
                ('headers', models.TextField(null=True)),
                ('params', models.TextField(null=True)),
                ('body', models.TextField(null=True)),
                ('createdon', models.DateTimeField(null=False)),
                ('createdby', models.CharField(max_length=50, null=True)),
                ('ind_activo', models.SmallIntegerField(default=1)),
                ('modifiedon', models.DateTimeField(null=True)),
                ('modifiedby', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'connections',
            },
        ),

        migrations.RunPython(insert_connections)
    ]
