# Generated by Django 4.2.5 on 2023-10-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='createdon',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='method',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='process',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
